version: '2.4'
services:

    patruapi:
        container_name: patruapi
        image: patruapi
        restart: always
        ports:
            - "5002:5000"
        environment:
            - TZ="America/Sao_Paulo"
        networks:
            - patrulha

##### ===== REDE ===== #####

networks:
    patrulha:
        driver: bridge
